services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    build: .
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc/odoo.conf:/etc/odoo/odoo.conf
      - odoo-data:/var/lib/odoo
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

volumes:
  pg-data:
  odoo-data:
